### ISSUE TITLE
Add explicit license to the repository

### ISSUE THREAD

**Issue by oleg-nenashev** [librecores/librecores-pipeline-lib#11]
Currently there is no license defined. I suggest adding a MIT license like in https://github.com/librecores/librecores-ci-jenkins-server/blob/master/LICENSE

**Comment by acupoftee** [comment]
I'll be happy to add a license for this if no one else is currently working on it.

**Comment by DanTm99** [comment]
#14

**Comment by Nancy-Chauhan** [comment]
Lets close this issue @oleg-nenashev!
